#!/bin/bash
#Autor: Anton Dalmau

arrIfaces=()

function getIfaces() {
    for iface in $(ip a | cut -d ' ' -f2| cut -d '@' -f1 | tr ':' '\n' | awk NF)
    do
        arrIfaces+=("$iface")
    done
}

function showIfaces() {
    count=0
    for i in "${arrIfaces[@]}"
    do
       echo "$count. $i"
       (( count++ ))
    done
}


clear

tput setaf 119
echo "-------------------------------------------------"
echo "            CONFIGURACIÓ DE VLANs                "
echo "-------------------------------------------------"
printf "\nSobre quina interfície vols treballar?\n"
getIfaces
showIfaces
tput sgr0
read ifaceNumber
tput setaf 119
iface="${arrIfaces[ifaceNumber]}"
echo "Quina acció vols? [add] [del] [up] [down]"
tput sgr0
read action

if [[ $action == "add" || $action == "a" ]]
then
    tput setaf 119
    echo "ID de la VLAN:"
    tput sgr0
    read idvlan
    #sudo vconfig add $iface $idvlan
    sudo ip l add link $iface name $iface.$idvlan type vlan id $idvlan
    tput setaf 119
    echo "Vols DHCP? [s/n]"
    tput sgr0
    read dhcp
    if [[ $dhcp == "s" ]]
    then
        sudo dhclient $iface.$idvlan
    else
        tput setaf 119
        echo "Escriu la IP:"
        tput sgr0
        read ip
        sudo ip addr add $ip dev $iface.$idvlan
    fi
    sudo ip link set $iface up
    sudo ip link set $iface.$idvlan up
    notify-send "VLAN $idvlan afegida"
elif [[ $action == "del" || $action == "d" ]]
then
    #sudo vconfig rem $iface.$idvlan
    sudo ip link delete $iface
    notify-send "VLAN $idvlan eliminada"
elif [[ $action == "up" || $action == "u" ]]
then
    sudo ip link set $iface up
    notify-send "$iface up"
elif [[ $action == "down" || $action == "do" ]]
then
    sudo ip link set $iface down
    notify-send "$iface down"
else
    tput setaf 196
    echo "ERROR: acció incorrecta."
    tput sgr0
fi

ip -c a
route -n
